name: integration

on: pull_request


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Checkout sentry repository
        uses: actions/checkout@v2
        with:
          repository: getsentry/sentry
          path: sentry
          ref: disable-eslint-rule-withRouter

      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '16'

      - name: Setup Dependencies
        run: yarn install

        # We add the package instead of linking here because we need to make
        # sure all dependencies are synced as well, which link will not do.
      - name: Install sentry dependencies
        run: |
          cd sentry
          yarn install
          yarn add -D ../packages/eslint-config-sentry-app

      - name: Run lint in sentry
        env:
          SENTRY_ESLINT_RELAXED: 1
        run: |
          cd sentry
          yarn lint
