name: npm publish

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '20'
          registry-url: https://registry.npmjs.org/
      - name: Install Depdendencies
        run: |
          yarn install --frozen-lockfile
      - name: Bootstrap lerna
        run: |
          yarn lerna bootstrap
      - name: Run Tests
        run: |
          yarn test
      - name: Publish
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          yarn lerna publish minor -y --force-publish=* --conventional-commits
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
